'use strict';
// Run with VS Code --extensionTestsPath and the current compiler in nagi.compilerPath.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vscode = require('vscode');
const { fixtures } = require('./actor-fixtures');

module.exports.run = async () => {
  const root = path.resolve(__dirname, '../../..');
  const folder = path.join(root, 'build', 'vscode-actor-host');
  fs.mkdirSync(folder, { recursive: true });
  const extension = vscode.extensions.getExtension('Disnana.nagi-lang');
  assert.ok(extension);
  await extension.activate();
  let cases = 0;
  const hoverText = hovers => hovers.flatMap(hover => hover.contents.map(content => content.value || String(content))).join('\n');
  for (const [suffix, text] of fixtures) {
    const file = path.join(folder, `main.${suffix}`);
    fs.writeFileSync(file, text);
    const doc = await vscode.workspace.openTextDocument(file);
    await vscode.window.showTextDocument(doc);
    const handle = text.indexOf('Handle[i64') + 2;
    const types = await vscode.commands.executeCommand('vscode.executeCompletionItemProvider', doc.uri, doc.positionAt(handle));
    const actor = types.items.find(item => item.label === 'Handle');
    const turn = types.items.find(item => item.label === 'Step');
    assert.equal(actor.insertText.value, 'Handle', 'existing type brackets are not repeated');
    assert.equal(turn.insertText.value, 'Step', 'another completion at the same bracket preserves it');
    assert.match(actor.detail, /resource Handle\[M, R, E\]/);
    assert.match(turn.detail, /resource Step\[S, R, E\]/);
    cases++;
    const constant = text.lastIndexOf('actors.CallKind.MAILBOX_FULL') + 'actors.CallKind.'.length;
    const list = await vscode.commands.executeCommand('vscode.executeCompletionItemProvider', doc.uri, doc.positionAt(constant + 2));
    const full = list.items.find(item => item.label === 'MAILBOX_FULL');
    assert.ok(full);
    assert.equal(full.kind, vscode.CompletionItemKind.Constant);
    const hover = await vscode.commands.executeCommand('vscode.executeHoverProvider', doc.uri, doc.positionAt(constant + 2));
    assert.match(hoverText(hover), /actors.CallKind.MAILBOX_FULL: actors.CallKind/);
    cases++;
    const targets = await vscode.commands.executeCommand('vscode.executeDefinitionProvider', doc.uri, doc.positionAt(constant + 2));
    assert.equal(targets[0].uri.scheme, 'nagi-stdlib');
    assert.equal(targets[0].uri.path, '/std/actor.nagi');
    const virtual = await vscode.workspace.openTextDocument(targets[0].uri);
    assert.match(virtual.lineAt(targets[0].range.start.line).text, /MAILBOX_FULL: CallKind/);
    cases++;
    for (const [operation, result, module] of [['actors.default_options', 'ActorConfig', '/std/actor.nagi'], ['http.default_options', 'HttpConfig', '/std/http/server.nagi']]) {
      const offset = text.indexOf(operation) + operation.lastIndexOf('.') + 1;
      const signature = await vscode.commands.executeCommand('vscode.executeSignatureHelpProvider', doc.uri, doc.positionAt(offset + 'default_options('.length));
      assert.match(signature.signatures[0].label, new RegExp(`-> ${result}$`));
      const targets = await vscode.commands.executeCommand('vscode.executeDefinitionProvider', doc.uri, doc.positionAt(offset + 2));
      assert.equal(targets[0].uri.path, module);
      cases++;
    }
    const field = text.indexOf('event.child_name') + 'event.'.length;
    const members = await vscode.commands.executeCommand('vscode.executeCompletionItemProvider', doc.uri, doc.positionAt(field + 2));
    assert.match(members.items.find(item => item.label === 'child_name').detail, /view\[str\].*read-only/);
    assert.ok(members.items.some(item => item.label === 'lost_events'));
    assert.ok(!members.items.some(item => item.label === 'STOPPED'));
    const targetsField = await vscode.commands.executeCommand('vscode.executeDefinitionProvider', doc.uri, doc.positionAt(field + 2));
    assert.equal(targetsField[0].uri.path, '/std/actor.nagi');
    cases++;
    const call = text.indexOf('actors.call(') + 'actors.'.length;
    const signature = await vscode.commands.executeCommand('vscode.executeSignatureHelpProvider', doc.uri, doc.positionAt(call + 'call('.length));
    assert.match(signature.signatures[0].label, /Future\[Result\[Result\[R, E\], actors.CallError\]\]/);
    assert.equal(signature.signatures[0].parameters.length, 4);
    cases++;
  }
  const dependency = path.join(folder, 'helper.nagi');
  const original = 'import std.actor as actors\ndef missing() -> actors.CallKind:\n    return actors.CallKind.NOT_READY\n';
  fs.writeFileSync(dependency, original);
  const dep = await vscode.workspace.openTextDocument(dependency);
  const fresh = '# unsaved 😀\n' + original.replace('NOT_READY', 'STOPPED');
  const edit = new vscode.WorkspaceEdit();
  edit.replace(dep.uri, new vscode.Range(dep.positionAt(0), dep.positionAt(dep.getText().length)), fresh);
  assert.ok(await vscode.workspace.applyEdit(edit));
  await vscode.window.showTextDocument(dep);
  const stopped = fresh.indexOf('CallKind.STOPPED') + 'CallKind.'.length;
  const targets = await vscode.commands.executeCommand('vscode.executeDefinitionProvider', dep.uri, dep.positionAt(stopped + 2));
  assert.equal(targets[0].uri.path, '/std/actor.nagi');
  assert.equal(fs.readFileSync(dependency, 'utf8'), original);
  cases++;
  const importFile = path.join(folder, 'import-edit.nagi');
  fs.writeFileSync(importFile, 'def main():\n    print("hello")\n');
  const importDoc = await vscode.workspace.openTextDocument(importFile);
  await vscode.window.showTextDocument(importDoc);
  const prefix = 'import std.';
  const importEdit = new vscode.WorkspaceEdit();
  importEdit.replace(importDoc.uri, new vscode.Range(importDoc.positionAt(0), importDoc.positionAt(importDoc.getText().length)), prefix);
  assert.ok(await vscode.workspace.applyEdit(importEdit));
  const imports = await vscode.commands.executeCommand('vscode.executeCompletionItemProvider', importDoc.uri, importDoc.positionAt(prefix.length));
  assert.ok(imports.items.some(item => item.label === 'std.actor'));
  assert.ok(imports.items.some(item => item.label === 'std.http.server'));
  cases++;
  const result = process.env.NAGI_EDITOR_HOST_RESULT || path.join(root, 'build', 'vscode-actor-host-result.json');
  fs.writeFileSync(result, JSON.stringify({ passed: true, cases }, null, 2));
};
