'use strict';
// Run with VS Code --extensionTestsPath and the current compiler in nagi.compilerPath.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vscode = require('vscode');
const { fixtures } = require('./stdlib-fixtures');

module.exports.run = async () => {
  const root = path.resolve(__dirname, '../../..');
  const folder = process.env.NAGI_EDITOR_HOST_FIXTURES || path.join(root, 'build', 'vscode-stdlib-host');
  fs.mkdirSync(folder, { recursive: true });
  const extension = vscode.extensions.getExtension('Disnana.nagi-lang');
  assert.ok(extension);
  await extension.activate();
  let cases = 0;
  const hoverText = hovers => hovers.flatMap(hover => hover.contents.map(content => content.value || String(content))).join('\n');
  for (const [suffix, text] of fixtures) {
    const file = path.join(folder, `main.${suffix}`);
    fs.writeFileSync(file, text);
    const doc = await vscode.workspace.openTextDocument(file);
    await vscode.window.showTextDocument(doc);
    const status = text.indexOf('Code.UNAUTHORIZED') + 'Code.'.length;
    const list = await vscode.commands.executeCommand('vscode.executeCompletionItemProvider', doc.uri, doc.positionAt(status + 2));
    const unauthorized = list.items.find(item => item.label === 'UNAUTHORIZED');
    assert.ok(unauthorized, `${suffix}: standard constants missing`);
    assert.equal(unauthorized.kind, vscode.CompletionItemKind.Constant);
    assert.equal(unauthorized.insertText.value || unauthorized.insertText, 'UNAUTHORIZED');
    assert.ok(list.items.some(item => item.label === 'CONTENT_TOO_LARGE'));
    assert.ok(!list.items.some(item => item.label === 'CONTINUE'), 'informational status is not a final response');
    cases++;
    const hover = await vscode.commands.executeCommand('vscode.executeHoverProvider', doc.uri, doc.positionAt(status + 2));
    assert.match(hoverText(hover), /Code.UNAUTHORIZED: Code/);
    cases++;
    const definition = await vscode.commands.executeCommand('vscode.executeDefinitionProvider', doc.uri, doc.positionAt(status + 2));
    assert.equal(definition[0].uri.scheme, 'nagi-stdlib');
    const virtual = await vscode.workspace.openTextDocument(definition[0].uri);
    assert.match(virtual.lineAt(definition[0].range.start.line).text, /UNAUTHORIZED: Status/);
    assert.equal(virtual.isDirty, false);
    cases++;
    const call = text.indexOf('http.text') + 'http.'.length;
    const signature = await vscode.commands.executeCommand('vscode.executeSignatureHelpProvider', doc.uri, doc.positionAt(call + 'text('.length));
    assert.equal(signature.signatures[0].label, `${suffix === 'low' ? 'fn' : 'def'} http.text(status: Code, body: view[str]) -> http.Response`);
    assert.equal(signature.signatures[0].parameters[1].label, 'body: view[str]');
    cases++;
    const jsonCall = text.indexOf('http.is_json_content_type') + 'http.'.length;
    const jsonMembers = await vscode.commands.executeCommand('vscode.executeCompletionItemProvider', doc.uri, doc.positionAt(jsonCall + 2));
    const jsonItem = jsonMembers.items.find(item => item.label === 'is_json_content_type');
    assert.equal(jsonItem.kind, vscode.CompletionItemKind.Function);
    assert.equal(jsonItem.insertText.value, 'is_json_content_type', 'an existing call keeps its argument list');
    const jsonHover = await vscode.commands.executeCommand('vscode.executeHoverProvider', doc.uri, doc.positionAt(jsonCall + 2));
    assert.match(hoverText(jsonHover), /is_json_content_type\(request: view\[Incoming\]\) -> Result\[bool, Error\]/);
    const jsonSignature = await vscode.commands.executeCommand('vscode.executeSignatureHelpProvider', doc.uri,
      doc.positionAt(jsonCall + 'is_json_content_type('.length));
    assert.equal(jsonSignature.signatures[0].label,
      `${suffix === 'low' ? 'fn' : 'def'} http.is_json_content_type(request: view[Incoming]) -> Result[bool, Error]`);
    const jsonDefinition = await vscode.commands.executeCommand('vscode.executeDefinitionProvider', doc.uri, doc.positionAt(jsonCall + 2));
    assert.equal(jsonDefinition[0].uri.scheme, 'nagi-stdlib');
    const jsonSource = await vscode.workspace.openTextDocument(jsonDefinition[0].uri);
    assert.match(jsonSource.lineAt(jsonDefinition[0].range.start.line).text, /is_json_content_type/);
    cases++;
    const typeOffset = text.indexOf('http.Response') + 'http.'.length;
    const types = await vscode.commands.executeCommand('vscode.executeCompletionItemProvider', doc.uri, doc.positionAt(typeOffset + 2));
    assert.equal(types.items.find(item => item.label === 'Request').insertText.value, 'Request');
    assert.equal(types.items.find(item => item.label === 'App').insertText.value, 'App[${1:S}, ${2:E}]');
    assert.ok(!types.items.some(item => item.label === 'text'));
    cases++;
    const field = text.indexOf('request.path') + 'request.'.length;
    const fields = await vscode.commands.executeCommand('vscode.executeCompletionItemProvider', doc.uri, doc.positionAt(field + 2));
    assert.match(fields.items.find(item => item.label === 'path').detail, /view\[str\].*read-only/);
    assert.ok(fields.items.some(item => item.label === 'is_get'));
    assert.ok(!fields.items.some(item => item.label === 'GET'));
    const pathTarget = await vscode.commands.executeCommand('vscode.executeDefinitionProvider', doc.uri, doc.positionAt(field + 2));
    assert.equal(pathTarget[0].uri.scheme, 'nagi-stdlib');
    cases++;
    const pattern = text.indexOf('Some(token)');
    const patterns = await vscode.commands.executeCommand('vscode.executeCompletionItemProvider', doc.uri, doc.positionAt(pattern + 2));
    assert.ok(patterns.items.some(item => item.label === 'Some'));
    assert.ok(patterns.items.some(item => item.label === 'None'));
    const token = text.indexOf('print(token)') + 'print('.length;
    const tokenHover = await vscode.commands.executeCommand('vscode.executeHoverProvider', doc.uri, doc.positionAt(token + 2));
    assert.match(hoverText(tokenHover), /token: view\[str\]/);
    cases++;
  }
  const dependency = path.join(folder, 'helper.nagi');
  const original = 'import std.http.server as http\ndef response_code() -> i64:\n    return http.Status.OK.value\n';
  fs.writeFileSync(dependency, original);
  const file = path.join(folder, 'overlay.nagi');
  const entry = 'import "helper.nagi" as helper\ndef main():\n    print(helper.response_code())\n';
  fs.writeFileSync(file, entry);
  const main = await vscode.workspace.openTextDocument(file);
  const dep = await vscode.workspace.openTextDocument(dependency);
  const fresh = '# unsaved 😀\n' + original.replace('Status.OK', 'Status.CREATED');
  const edit = new vscode.WorkspaceEdit();
  edit.replace(dep.uri, new vscode.Range(dep.positionAt(0), dep.positionAt(dep.getText().length)), fresh);
  assert.ok(await vscode.workspace.applyEdit(edit));
  await vscode.window.showTextDocument(dep);
  const offset = fresh.indexOf('Status.CREATED') + 'Status.'.length;
  const definitions = await vscode.commands.executeCommand('vscode.executeDefinitionProvider', dep.uri, dep.positionAt(offset + 2));
  assert.equal(definitions[0].uri.scheme, 'nagi-stdlib');
  const virtual = await vscode.workspace.openTextDocument(definitions[0].uri);
  assert.match(virtual.lineAt(definitions[0].range.start.line).text, /CREATED: Status/);
  assert.equal(fs.readFileSync(dependency, 'utf8'), original);
  assert.equal(fs.existsSync(path.join(folder, 'build', 'native')), false);
  await vscode.window.showTextDocument(main);
  cases++;
  const importFile = path.join(folder, 'import-edit.nagi');
  fs.writeFileSync(importFile, 'def main():\n    print("hello")\n');
  const importDoc = await vscode.workspace.openTextDocument(importFile);
  await vscode.window.showTextDocument(importDoc);
  for (const [code, label] of [['import std.http.', 'std.http.server'], ['from std.http.server import Req', 'Request']]) {
    const edit = new vscode.WorkspaceEdit();
    edit.replace(importDoc.uri, new vscode.Range(importDoc.positionAt(0), importDoc.positionAt(importDoc.getText().length)), code);
    assert.ok(await vscode.workspace.applyEdit(edit));
    const list = await vscode.commands.executeCommand('vscode.executeCompletionItemProvider', importDoc.uri, importDoc.positionAt(code.length));
    const item = list.items.find(item => item.label === label);
    assert.ok(item, `initial import completion ${label}`);
    assert.equal(item.insertText.value || item.insertText, label);
    if (label === 'std.http.server') assert.equal(item.range.start.character, 'import '.length);
    cases++;
  }
  const result = process.env.NAGI_EDITOR_HOST_RESULT || path.join(root, 'build', 'vscode-stdlib-host-result.json');
  fs.writeFileSync(result, JSON.stringify({ passed: true, cases }, null, 2));
};
