[package]
name = "nagi-generated-a7e8585e68817ad2"
version = "0.1.0"
edition = "2021"
autobins = false

[[bin]]
name = "nagi-a7e8585e68817ad2-g-e06a6-18dce7cd3f12c28e-0"
path = "src/main.rs"

[workspace]

[dependencies.nagi-runtime]
path = "../../../../runtime"

[profile.release]
opt-level = 3
lto = false
codegen-units = 1
panic = "unwind"
